# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'message',
            name = 'dialog_id',
            field =  models.IntegerField(default=0)
        )
    ]
