# Generated by Django 2.0 on 2017-12-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20171122_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'dialog_id', 'ordering': ['created_at', 'from_user'], 'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='message',
            name='dialog_id',
            field=models.IntegerField(default=0, verbose_name='Диалог'),
        ),
    ]
