# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'Коллектив', 'verbose_name_plural': 'Коллективы'},
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to=team.models.logo_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='team',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Активны'),
        ),
    ]
