# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20171003_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
