# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20171003_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
