# Generated by Django 2.0 on 2017-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='tags',
            field=models.ManyToManyField(related_name='blog_tags', related_query_name='place_tag', to='tag.Tag', verbose_name='Тэги'),
        ),
    ]
