# Generated by Django 2.0 on 2018-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20171228_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='tags',
            field=models.ManyToManyField(related_name='band_tags', related_query_name='band_tag', to='tag.Tag', verbose_name='Тэги'),
        ),
    ]
