# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.avatar_path, verbose_name='Аватар'),
        ),
    ]
