# Generated by Django 2.0 on 2017-12-24 11:15

from django.db import migrations
import django.contrib.postgres.fields.jsonb

class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171011_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='prefer_styles',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Предпочитаемые стили'),
        ),
    ]
