# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 10:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171009_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
