# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171017_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rubric',
            field=models.CharField(choices=[('imho', 'Личное мнение'), ('festivals', 'Фестивали'), ('music', 'Музыка')], default='imho', max_length=32, verbose_name='Рубрика'),
        ),
    ]
