# Generated by Django 2.0 on 2017-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('blog', '0008_auto_20171227_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blog_tags', related_query_name='blog_tag', to='tag.Tag', verbose_name='Тэги'),
        ),
    ]
