# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('image', models.ImageField(upload_to=event.models.img_path, verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published', models.BooleanField(default=False, verbose_name='Активно')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'События',
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
