# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20171009_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(blank=True, related_name='event_bands', to='band.Band', verbose_name='Команды'),
        ),
        migrations.AlterField(
            model_name='event',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='event_musicians', to=settings.AUTH_USER_MODEL, verbose_name='Музыканты'),
        ),
    ]
