# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20171009_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
