# Generated by Django 2.0 on 2018-01-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20171227_1751'),
    ]

    operations = [
         migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(related_name='event_place', to='place.Place', verbose_name='Место проведения'),
        ),
    ]
