# Generated by Django 2.0 on 2018-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='event_location', to='place.Place', verbose_name='Место проведения'),
        ),
    ]
