# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import place.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=240, verbose_name='Адрес')),
                ('logo', models.ImageField(upload_to=place.models.logo_path, verbose_name='Логотип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published', models.BooleanField(default=False, verbose_name='Активно')),
                ('slug', models.SlugField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коллектив',
                'verbose_name_plural': 'Коллективы',
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
