# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20171003_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
