# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20171009_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='place_musicians', to=settings.AUTH_USER_MODEL, verbose_name='Музыканты заведения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
