# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20171009_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='maps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='location',
            name='worktime',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о работе'),
        ),
    ]
