# Generated by Django 2.0 on 2017-12-27 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20171102_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
