# Generated by Django 2.0 on 2017-12-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20171102_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='maps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='place',
            name='worktime',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о работе'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Расположение'),
        ),
    ]
