# Generated by Django 2.0 on 2017-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('place', '0007_auto_20171227_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='place_tags', related_query_name='place_tag', to='tag.Tag', verbose_name='Тэги'),
        ),
    ]
