# Generated by Django 2.0 on 2018-01-07 13:34

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20171227_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AddField(
            model_name='place',
            name='worktime',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о работе'),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Вермя работы'),
        ),
    ]
