# Generated by Django 2.0 on 2018-01-14 15:47

from django.db import migrations, models
import place.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_place_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='icon',
            field=models.ImageField(blank=True, upload_to=place.models.icon_path, verbose_name='Иконка'),
        ),
    ]
