# Generated by Django 2.0.3 on 2018-04-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import playlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20180120_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=playlist.models.image_path, verbose_name='Титульное изображение'),
        ),
    ]
